# Generated by Django 4.2.19 on 2025-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArquivoProcessado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo_original", models.FileField(upload_to="uploads/")),
                (
                    "arquivo_processado",
                    models.FileField(blank=True, null=True, upload_to="processados/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
